version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      - TZ=Asia/Seoul
    container_name: diarypic-mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    networks: [diarypic-net]

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diarypic-backend
    depends_on:
      db:
        condition: service_healthy # DBê°€ ì¤€ë¹„ëœ í›„ ì‹œì‘
    ports:
      - "8080:8080"
    env_file: # backend ì„œë¹„ìŠ¤ê°€ ì‚¬ìš©í•  í™˜ê²½ ë³€ìˆ˜ íŒŒì¼ì„ ì§€ì •
      - .env
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    networks: [diarypic-net]

  ai-server:
    build:
      context: ../ai-server  # ğŸ“ FastAPI ì½”ë“œê°€ ìˆëŠ” ë””ë ‰í† ë¦¬ ê²½ë¡œ
      dockerfile: Dockerfile  # ai-server/Dockerfileì´ ìˆì–´ì•¼ í•¨
    container_name: diarypic-ai-server
    ports:
      - "8000:8000"
    env_file:
      - ../ai-server/.env  # ğŸ“„ OpenAI API í‚¤ ë“± í™˜ê²½ ë³€ìˆ˜ ì„¤ì •
    restart: unless-stopped
    networks: [ diarypic-net ]


networks:
  diarypic-net:
    driver: bridge

volumes:
  mysql_data:
    driver: local